"""Categorized creative-direction presets shared by all image workspaces."""

from __future__ import annotations


VISUAL_DIRECTION_PRESETS: dict[str, tuple[str, ...]] = {
    "Mood and emotional tone": (
        "serene and contemplative",
        "warm and comforting",
        "joyful and celebratory",
        "playful and whimsical",
        "romantic and tender",
        "hopeful and uplifting",
        "nostalgic and bittersweet",
        "melancholic and introspective",
        "lonely and isolated",
        "somber and mournful",
        "tense and anticipatory",
        "anxious and claustrophobic",
        "ominous and foreboding",
        "eerie and uncanny",
        "mysterious and enigmatic",
        "dreamlike and ethereal",
        "surreal and disorienting",
        "epic and awe-inspiring",
        "heroic and triumphant",
        "rebellious and defiant",
        "raw and confrontational",
        "chaotic and overwhelming",
        "energetic and exhilarating",
        "quiet and observational",
        "clinical and detached",
        "elegant and refined",
        "luxurious and aspirational",
        "gritty and hard-edged",
        "rustic and grounded",
        "sacred and reverent",
        "absurd and deadpan",
        "darkly comedic",
    ),
    "Lighting": (
        "soft diffused daylight",
        "bright overcast daylight",
        "hard direct noon sunlight",
        "warm golden-hour sunlight",
        "cool blue-hour ambient light",
        "low sunrise backlight",
        "deep sunset side light",
        "moonlit night illumination",
        "starlight with minimal fill",
        "soft window light",
        "north-facing studio window light",
        "doorway light cutting into darkness",
        "skylight from directly above",
        "dappled sunlight through foliage",
        "volumetric sunbeams through haze",
        "dramatic single-source side light",
        "Rembrandt portrait lighting",
        "butterfly beauty lighting",
        "split-face portrait lighting",
        "broad frontal beauty light",
        "soft clamshell beauty lighting",
        "high-key studio lighting",
        "low-key chiaroscuro lighting",
        "three-point studio lighting",
        "large softbox key with gentle fill",
        "hard spotlight with rapid falloff",
        "silhouette against a bright background",
        "strong rim light around the subject",
        "colored edge lights from both sides",
        "practical lamps as motivated sources",
        "warm candlelight",
        "flickering firelight",
        "neon storefront lighting",
        "mixed neon magenta and cyan light",
        "fluorescent office ceiling light",
        "sodium-vapor street lighting",
        "headlights cutting through darkness",
        "projector light across the subject",
        "underlighting for an uncanny effect",
        "top lighting with deep eye shadows",
        "product light tent with clean reflections",
        "glossy commercial strip-light reflections",
        "caustic reflections from water",
        "bioluminescent environmental glow",
        "lightning-flash illumination",
        "screen glow on the face",
        "laser and stage-beam lighting",
        "soft global illumination with bounced color",
    ),
    "Color palette": (
        "warm earth tones",
        "cool desaturated blues",
        "neutral natural colors",
        "muted pastel palette",
        "bright candy colors",
        "soft powdery pastels",
        "rich jewel tones",
        "deep autumnal colors",
        "fresh spring greens and blossoms",
        "sun-bleached summer colors",
        "icy winter whites and blues",
        "monochrome black and white",
        "warm monochrome sepia",
        "single-color monochrome treatment",
        "near-monochrome with one accent color",
        "complementary orange and teal",
        "complementary red and cyan",
        "complementary violet and yellow",
        "analogous warm palette",
        "analogous cool palette",
        "triadic primary-color palette",
        "limited two-color print palette",
        "high-saturation pop palette",
        "low-saturation cinematic palette",
        "dark palette with luminous accents",
        "high-key whites and pale neutrals",
        "black, gold, and ivory luxury palette",
        "industrial gray with safety-color accents",
        "natural skin tones with restrained surroundings",
        "iridescent spectral color",
        "infrared false-color palette",
        "vintage faded color palette",
    ),
    "Time and season": (
        "pre-dawn darkness",
        "first light before sunrise",
        "early morning",
        "late morning",
        "bright midday",
        "late afternoon",
        "golden hour",
        "sunset",
        "twilight",
        "blue hour",
        "early evening",
        "deep night",
        "midnight",
        "timeless studio setting",
        "early spring",
        "lush late spring",
        "high summer",
        "late-summer heat",
        "early autumn",
        "peak autumn foliage",
        "late autumn",
        "first winter frost",
        "deep winter",
        "seasonal transition",
    ),
    "Weather and atmosphere": (
        "clear dry air",
        "soft scattered clouds",
        "dramatic storm clouds",
        "heavy overcast sky",
        "light drizzle",
        "steady rain",
        "torrential rain",
        "rain immediately after a storm",
        "distant thunderstorm",
        "electrical storm with lightning",
        "light snowfall",
        "heavy blowing snow",
        "blizzard whiteout",
        "morning ground fog",
        "dense enveloping fog",
        "low valley mist",
        "humid tropical haze",
        "dry desert heat shimmer",
        "dust suspended in the air",
        "windblown sand",
        "smoke-filled atmosphere",
        "fine indoor haze",
        "sea spray and salt mist",
        "visible breath in cold air",
        "wind moving hair, fabric, and foliage",
        "still air with no visible movement",
        "wet reflective surfaces",
        "frost-covered surfaces",
        "floating pollen and seeds",
        "embers and drifting ash",
        "underwater suspended particles",
        "high-altitude thin atmosphere",
    ),
    "Composition and hierarchy": (
        "centered symmetrical composition",
        "asymmetrical balanced composition",
        "rule-of-thirds placement",
        "golden-ratio spiral composition",
        "strong diagonal composition",
        "triangular subject arrangement",
        "circular composition",
        "radial composition",
        "layered foreground, middle ground, and background",
        "deep composition with multiple spatial planes",
        "flat graphic composition",
        "minimal composition with generous negative space",
        "dense maximalist composition",
        "single dominant focal subject",
        "small subject within a vast environment",
        "frame-within-a-frame composition",
        "leading lines toward the subject",
        "repeating shapes and visual rhythm",
        "balanced visual counterweights",
        "foreground occlusion for depth",
        "overlapping silhouettes",
        "strong horizon division",
        "low horizon emphasizing the sky",
        "high horizon emphasizing the ground",
        "off-center tension with active empty space",
        "isolated subject surrounded by emptiness",
        "compressed crowd composition",
        "clean product-centered composition",
        "editorial composition with copy-safe space",
        "poster-like iconic silhouette",
        "environmental storytelling around the subject",
        "controlled visual path from subject to secondary detail",
    ),
    "Depth and focus": (
        "deep focus from foreground to background",
        "shallow depth of field",
        "extremely shallow focus plane",
        "sharp subject with softly blurred background",
        "foreground blur framing a sharp subject",
        "background subject in focus with foreground blur",
        "selective focus on the eyes",
        "selective focus on the hands or held object",
        "selective focus on a material detail",
        "macro focus with rapid falloff",
        "split-diopter near-and-far focus",
        "tilt-shift selective focus",
        "soft atmospheric depth",
        "aerial perspective across distant layers",
        "crisp flat focus for graphic clarity",
        "dreamy diffusion around highlights",
        "soft-focus portrait rendering",
        "razor-sharp commercial detail",
        "motion-blurred background with sharp subject",
        "intentional full-frame motion blur",
        "rack-focus transition moment",
        "miniature-effect depth of field",
    ),
    "Motion and energy": (
        "completely still and poised",
        "quiet natural micro-movement",
        "gentle flowing motion",
        "wind-driven movement",
        "suspended peak-action instant",
        "decisive contact moment",
        "explosive outward motion",
        "strong forward momentum",
        "rapid lateral movement",
        "spiraling rotational motion",
        "falling motion",
        "rising or launching motion",
        "impact with visible material response",
        "fabric and hair trailing the movement",
        "particles tracing the action path",
        "controlled panning blur",
        "long-exposure light trails",
        "stroboscopic repeated-motion effect",
        "freeze-frame high-speed clarity",
        "handheld immediacy",
        "smooth gliding cinematic movement",
        "chaotic multi-directional energy",
        "rhythmic choreographed movement",
        "slow-motion weight and detail",
    ),
    "Environment and spatial character": (
        "clean seamless studio",
        "intimate domestic interior",
        "lived-in cluttered room",
        "minimal modern interior",
        "grand historic interior",
        "industrial working space",
        "abandoned decaying structure",
        "sterile laboratory",
        "crowded urban street",
        "quiet empty street",
        "dense old-city alley",
        "monumental civic space",
        "vast open landscape",
        "enclosed forest interior",
        "lush overgrown environment",
        "arid desert expanse",
        "rugged mountain terrain",
        "coastal shoreline",
        "underwater environment",
        "subterranean cavern",
        "high-altitude environment",
        "confined claustrophobic space",
        "maze-like layered space",
        "open airy architecture",
        "retro-futurist environment",
        "functional science-fiction environment",
        "coherent fantasy environment",
        "abstract symbolic space",
        "miniature handcrafted set",
        "stage or theatrical set",
    ),
    "Surface and texture": (
        "clean polished surfaces",
        "matte powdery surfaces",
        "high-gloss reflective surfaces",
        "brushed metal texture",
        "weathered oxidized metal",
        "clear and frosted glass contrast",
        "translucent subsurface materials",
        "soft woven textile detail",
        "heavy rough fabric",
        "wet fabric and surfaces",
        "aged cracked leather",
        "polished stone and marble",
        "rough natural stone",
        "raw unfinished wood",
        "lacquered wood",
        "smooth ceramic glaze",
        "rough handmade ceramic",
        "paper fibers and deckled edges",
        "peeling paint and layered wear",
        "dust, scratches, and lived-in wear",
        "mud and environmental residue",
        "water droplets and condensation",
        "frost and crystalline ice",
        "organic skin and pore texture",
        "feathers, fur, and fine fibers",
        "iridescent pearlescent surfaces",
        "holographic reflective foil",
        "handcrafted imperfect materials",
    ),
    "Art direction and genre": (
        "naturalistic contemporary realism",
        "cinematic narrative realism",
        "documentary observational realism",
        "high-fashion editorial",
        "luxury commercial advertising",
        "clean product visualization",
        "romantic period drama",
        "historical epic",
        "film noir",
        "neo-noir",
        "psychological thriller",
        "gothic horror",
        "folk horror",
        "cosmic horror",
        "whimsical fantasy",
        "dark fantasy",
        "high fantasy",
        "grounded science fiction",
        "retro science fiction",
        "cyberpunk",
        "solarpunk",
        "steampunk",
        "dieselpunk",
        "post-apocalyptic",
        "utopian futurism",
        "surrealist dream logic",
        "magical realism",
        "storybook illustration",
        "graphic novel art direction",
        "manga art direction",
        "European comic-album art direction",
        "mid-century editorial illustration",
        "Art Deco design language",
        "Art Nouveau design language",
        "Bauhaus graphic design",
        "brutalist graphic design",
        "psychedelic poster art",
        "retro arcade aesthetic",
        "analog horror aesthetic",
        "handmade folk-art aesthetic",
    ),
    "Image finish and color grade": (
        "neutral true-to-life grade",
        "warm cinematic grade",
        "cool cinematic grade",
        "teal-and-orange cinematic grade",
        "bleach-bypass desaturated grade",
        "crushed blacks with strong contrast",
        "lifted blacks and faded contrast",
        "soft highlight rolloff",
        "bright airy high-key finish",
        "dark rich low-key finish",
        "clean modern digital finish",
        "fine-grain photographic finish",
        "coarse high-speed film grain",
        "vintage color-film response",
        "faded archival print",
        "instant-film color response",
        "cross-processed color",
        "black-and-white silver-gelatin finish",
        "high-contrast monochrome finish",
        "soft matte editorial finish",
        "glossy magazine finish",
        "painterly softened finish",
        "crisp hyper-detailed finish",
        "subtle bloom around highlights",
        "halation around bright sources",
        "vignetted frame edges",
        "chromatic aberration used sparingly",
        "clean edge-to-edge optical rendering",
    ),
    "Subject presentation": (
        "candid and unaware of the camera",
        "direct eye contact with the camera",
        "calm neutral presentation",
        "open approachable body language",
        "closed guarded body language",
        "confident grounded stance",
        "vulnerable restrained posture",
        "heroic low-angle presentation",
        "intimate close observational presentation",
        "formal posed portrait",
        "relaxed environmental portrait",
        "dynamic action-led presentation",
        "silhouette-led presentation",
        "identity obscured or anonymous",
        "face emphasized above all else",
        "hands and interaction emphasized",
        "wardrobe silhouette emphasized",
        "material and craftsmanship emphasized",
        "product function emphasized",
        "scale emphasized through human comparison",
        "isolated subject",
        "paired subjects with clear relationship",
        "ensemble with equal visual attention",
        "crowd with one readable focal subject",
    ),
    "Optical and atmospheric effects": (
        "clean optics without visible effects",
        "subtle lens flare",
        "strong anamorphic flare",
        "soft veiling glare",
        "dream-filter diffusion",
        "starburst highlights",
        "prismatic refraction",
        "rainbow dispersion through glass",
        "reflections used as a second visual layer",
        "mirror symmetry",
        "window reflections over the scene",
        "silhouettes through translucent material",
        "volumetric light shafts",
        "god rays through clouds",
        "bokeh light shapes",
        "projected patterns across surfaces",
        "caustic light patterns",
        "heat distortion",
        "underwater optical distortion",
        "fog-softened distant lights",
        "snow or rain streaks near the lens",
        "water droplets on the lens",
        "intentional fisheye distortion",
        "miniature tilt-shift illusion",
    ),
}

EXPLICIT_ADULT_VISUAL_DIRECTION_PRESETS: dict[str, tuple[str, ...]] = {
    "NSFW — Adult erotic tone": (
        "openly erotic and mutually desirous",
        "intimate and emotionally connected",
        "playfully seductive",
        "urgent and uninhibited",
        "tender adult sensuality",
        "raw adult passion",
        "luxurious boudoir eroticism",
        "quiet intimate afterglow",
        "romantic adult sensuality",
        "confident and provocative",
        "voyeuristic yet consensual",
        "softly vulnerable adult intimacy",
        "athletic and energetic adult eroticism",
        "decadent and hedonistic",
        "dreamlike erotic fantasy",
        "dark and mysterious adult desire",
        "candid spontaneous adult intimacy",
        "polished editorial eroticism",
        "gritty documentary adult intimacy",
        "surreal symbolic adult eroticism",
    ),
    "NSFW — Adult subject presentation": (
        "consenting adult partners with equally readable participation",
        "desire conveyed through eye contact expression and body response",
        "intimate touch and physical reactions emphasized",
        "sexual action shown with clear body mechanics and contact",
        "faces expressions and emotional connection kept visible",
        "adult anatomy described directly without euphemism",
        "mutual pleasure and responsive movement emphasized",
        "close observational framing of adult intimacy",
        "both adult faces visible during intimate contact",
        "distinct adult reactions and changing expressions emphasized",
        "hands contact points and body mechanics kept readable",
        "equal initiative between consenting adult partners",
        "one confident adult lead with clear willing response",
        "adult vulnerability balanced by visible trust",
        "solo adult pleasure centered without an implied observer",
        "multiple consenting adults arranged with no obscured participant",
        "adult climax shown through expression posture and muscle tension",
        "aftercare and emotional reconnection emphasized",
        "natural adult body variation presented without idealization",
        "stylized adult anatomy with coherent proportions",
    ),
    "NSFW — Erotic composition and hierarchy": (
        "adult faces and intimate contact share the focal hierarchy",
        "one decisive erotic action centered clearly",
        "layered adult bodies with unambiguous limb ownership",
        "diagonal composition following the direction of intimate movement",
        "triangular arrangement for three consenting adult participants",
        "close body framing with every critical contact point visible",
        "wide environmental intimacy with privacy cues around the adults",
        "mirror used to reveal a second adult expression",
        "foreground touch leading toward the partners' faces",
        "balanced two-person composition with equal visual agency",
        "negative space isolating the adult lovers from the setting",
        "overhead composition clarifying intertwined adult posture",
        "profile composition emphasizing kiss breath and proximity",
        "silhouette composition preserving clear adult body relationships",
        "centered symmetrical boudoir presentation",
        "off-center candid composition suggesting spontaneous intimacy",
        "afterglow composition built around relaxed connected posture",
        "solo adult composition focused on expression and hand movement",
    ),
    "NSFW — Erotic lighting": (
        "soft boudoir window light across bare adult skin",
        "warm bedside practical lighting with gentle falloff",
        "low-key chiaroscuro shaping intertwined adult bodies",
        "candlelight reflecting across flushed adult skin",
        "moonlight and warm interior light mixed across adult lovers",
        "soft clamshell beauty light for polished erotic portraiture",
        "narrow rim light tracing adult silhouettes",
        "diffused morning light for intimate afterglow",
        "neon magenta and cyan edge light for adult nightclub eroticism",
        "hard single-source light for raw adult intensity",
        "projected window-blind shadows across adult bodies",
        "steamy shower backlight with visible droplets",
        "golden-hour light for secluded outdoor adult intimacy",
        "soft overhead hotel light with warm reflected fill",
        "red practical light with controlled neutral skin highlights",
        "flickering fireplace light across relaxed adult lovers",
        "high-key editorial erotic lighting",
        "dark ambient light with selective highlights on contact and expression",
    ),
    "NSFW — Erotic palette and atmosphere": (
        "warm skin tones with deep burgundy accents",
        "black red and gold erotic palette",
        "soft blush cream and rose boudoir palette",
        "cool moonlit blue with warm skin contrast",
        "deep violet and amber adult nightclub palette",
        "neutral linen and natural skin palette",
        "high-contrast monochrome erotic treatment",
        "warm sepia intimate nostalgia",
        "desaturated documentary palette with natural skin color",
        "jewel-toned decadent erotic palette",
        "dark near-monochrome with red highlights",
        "bright airy morning-after palette",
        "humid steamy atmosphere around adult lovers",
        "fine haze catching erotic rim light",
        "rain and wet reflective surfaces around adult intimacy",
        "candle smoke and warm enclosed atmosphere",
        "clean studio atmosphere with controlled skin rendering",
        "dreamlike diffusion with pastel erotic color",
    ),
    "NSFW — Skin material and tactile detail": (
        "natural adult skin texture and subtle flush",
        "soft perspiration catching edge light",
        "massage oil creating controlled skin highlights",
        "water droplets tracking across adult skin",
        "fabric compression and rumpled bedding around adult bodies",
        "lace silk leather and bare skin shown as distinct materials",
        "goosebumps and fine body hair visible in close detail",
        "hand pressure and temporary skin indentation visible",
        "warm reflected color moving across adult skin",
        "wet hair and damp skin after shower intimacy",
        "smudged makeup and loosened hair after intense activity",
        "jewelry reflecting small highlights against bare skin",
        "soft focus transitions without plastic skin smoothing",
        "physically believable muscle tension and relaxation",
        "breath condensation in cold-air adult intimacy",
        "subtle post-climax trembling conveyed through posture",
    ),
    "NSFW — Erotic genre and finish": (
        "luxury boudoir photography",
        "candid adult lifestyle photography",
        "editorial erotic fashion photography",
        "fine-art adult nude photography",
        "gritty analog erotic photography",
        "soft-focus vintage adult cinema",
        "high-contrast monochrome erotic film still",
        "glossy adult magazine finish",
        "naturalistic documentary adult intimacy",
        "romantic painterly erotic illustration",
        "graphic-novel adult intimacy",
        "stylized anime-inspired adult erotic art",
        "surreal adult fantasy painting",
        "dark gothic adult eroticism",
        "futuristic neon adult eroticism",
        "classical sculpture-inspired adult study",
        "instant-film adult snapshot",
        "clean hyperreal adult rendering",
    ),
    "NSFW — Expression action and story emphasis": (
        "anticipation developing visibly into adult pleasure",
        "teasing adult contact escalating into urgent movement",
        "changing pace reflected in both adult expressions",
        "adult desire shown through gaze breath hands and posture",
        "pleasure building through a coherent sequence of body reactions",
        "adult confidence softening into vulnerable intimacy",
        "one adult reaction causing an immediate response from the other",
        "mutual adult initiative preserved throughout the action",
        "sexual intensity balanced by attentive emotional connection",
        "adult climax treated as a distinct expressive story beat",
        "contrasting adult reactions during a shared peak",
        "post-climax stillness following visible exertion",
        "adult aftercare completing the intimate narrative",
        "playful adult teasing continuing into afterglow",
        "adult trust deepening through a consensual power exchange",
        "solo adult pleasure progressing from restraint to release",
        "three adult participants maintaining readable reciprocal attention",
        "environmental details quietly implying what happened before",
    ),
}


def visual_preset_key(category: str, value: str) -> str:
    """Return the stable serialized key for one catalog entry."""

    return f"{category}\x1f{value}"


VISUAL_DIRECTION_PRESET_KEYS = frozenset(
    visual_preset_key(category, value)
    for category, values in VISUAL_DIRECTION_PRESETS.items()
    for value in values
)
EXPLICIT_ADULT_VISUAL_DIRECTION_PRESET_KEYS = frozenset(
    visual_preset_key(category, value)
    for category, values in EXPLICIT_ADULT_VISUAL_DIRECTION_PRESETS.items()
    for value in values
)
ALL_VISUAL_DIRECTION_PRESET_KEYS = (
    VISUAL_DIRECTION_PRESET_KEYS | EXPLICIT_ADULT_VISUAL_DIRECTION_PRESET_KEYS
)


def visual_direction_preset_catalog(
    *,
    explicit_nsfw: bool = False,
) -> dict[str, tuple[str, ...]]:
    """Return creative-direction presets visible under the active content mode."""

    if not explicit_nsfw:
        return VISUAL_DIRECTION_PRESETS
    return {**VISUAL_DIRECTION_PRESETS, **EXPLICIT_ADULT_VISUAL_DIRECTION_PRESETS}


def format_visual_direction_presets(
    selected_keys: list[str] | tuple[str, ...],
    *,
    explicit_nsfw: bool = False,
) -> str:
    """Format selected catalog keys as compact, category-bound direction text."""

    catalog = visual_direction_preset_catalog(explicit_nsfw=explicit_nsfw)
    selected = set(selected_keys)
    parts: list[str] = []
    for category, values in catalog.items():
        chosen = [
            value
            for value in values
            if visual_preset_key(category, value) in selected
        ]
        if chosen:
            parts.append(f"{category}: {', '.join(chosen)}")
    return ("; ".join(parts) + ".") if parts else ""
